const USStatesList = [
    { val: 'Alaska', abbr: 'AK', isChecked: false },
    { val: 'Alabama', abbr: 'AL', isChecked: false },
    { val: 'Arkansas', abbr: 'AR', isChecked: false },
    { val: 'American Samoa', abbr: 'AS', isChecked: false },
    { val: 'Arizona', abbr: 'AZ', isChecked: false },
    { val: 'California', abbr: 'CA', isChecked: false },
    { val: 'Colorado', abbr: 'CO', isChecked: false },
    { val: 'Connecticut', abbr: 'CT', isChecked: false },
    { val: 'District Of Columbia', abbr: 'DC', isChecked: false },
    { val: 'Delaware', abbr: 'DE', isChecked: false },
    { val: 'Florida', abbr: 'FL', isChecked: false },
    { val: 'Federated States Of Micronesia', abbr: 'FM', isChecked: false },
    { val: 'Georgia', abbr: 'GA', isChecked: false },
    { val: 'Guam', abbr: 'GU', isChecked: false },
    { val: 'Hawaii', abbr: 'HI', isChecked: false },
    { val: 'Iowa', abbr: 'IA', isChecked: false },
    { val: 'Idaho', abbr: 'ID', isChecked: false },
    { val: 'Illinois', abbr: 'IL', isChecked: false },
    { val: 'Indiana', abbr: 'IN', isChecked: false },
    { val: 'Kansas', abbr: 'KS', isChecked: false },
    { val: 'Kentucky', abbr: 'KY', isChecked: false },
    { val: 'Louisiana', abbr: 'LA', isChecked: false },
    { val: 'Massachusetts', abbr: 'MA', isChecked: false },
    { val: 'Maryland', abbr: 'MD', isChecked: false },
    { val: 'Maine', abbr: 'ME', isChecked: false },
    { val: 'Marshall Islands', abbr: 'MH', isChecked: false },
    { val: 'Michigan', abbr: 'MI', isChecked: false },
    { val: 'Minnesota', abbr: 'MN', isChecked: false },
    { val: 'Missouri', abbr: 'MO', isChecked: false },
    { val: 'Northern Mariana Islands', abbr: 'MP', isChecked: false },
    { val: 'Mississippi', abbr: 'MS', isChecked: false },
    { val: 'Montana', abbr: 'MT', isChecked: false },
    { val: 'North Carolina', abbr: 'NC', isChecked: false },
    { val: 'North Dakota', abbr: 'ND', isChecked: false },
    { val: 'Nebraska', abbr: 'NE', isChecked: false },
    { val: 'New Hampshire', abbr: 'NH', isChecked: false },
    { val: 'New Jersey', abbr: 'NJ', isChecked: false },
    { val: 'New Mexico', abbr: 'NM', isChecked: false },
    { val: 'Nevada', abbr: 'NV', isChecked: false },
    { val: 'New York', abbr: 'NY', isChecked: false },
    { val: 'Ohio', abbr: 'OH', isChecked: false },
    { val: 'Oklahoma', abbr: 'OK', isChecked: false },
    { val: 'Oregon', abbr: 'OR', isChecked: false },
    { val: 'Pennsylvania', abbr: 'PA', isChecked: false },
    { val: 'Puerto Rico', abbr: 'PR', isChecked: false },
    { val: 'Palau', abbr: 'PW', isChecked: false },
    { val: 'Rhode Island', abbr: 'RI', isChecked: false },
    { val: 'South Carolina', abbr: 'SC', isChecked: false },
    { val: 'South Dakota', abbr: 'SD', isChecked: false },
    { val: 'Tennessee', abbr: 'TN', isChecked: false },
    { val: 'Texas', abbr: 'TX', isChecked: false },
    { val: 'Utah', abbr: 'UT', isChecked: false },
    { val: 'Virginia', abbr: 'VA', isChecked: false },
    { val: 'Virgin Islands', abbr: 'VI', isChecked: false },
    { val: 'Vermont', abbr: 'VT', isChecked: false },    
    { val: 'Washington', abbr: 'WA', isChecked: false },
    { val: 'Wisconsin', abbr: 'WI', isChecked: false },
    { val: 'West Virginia', abbr: 'WV', isChecked: false },
    { val: 'Wyoming', abbr: 'WY', isChecked: false },
];

export default USStatesList;