import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
import welcomePic from '../images/GreenEarth1.jpg'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Image
        src={welcomePic}
        alt="Picture of the author"
        placeholder="blur"
        layout='fill'
      />
    </div>
  )
}

export default Home
